name: "Scans - Zap"
description: "Run zap scan"
inputs:
  type:
    description: "Type of ZAP scan (full or baseline)"
    required: false
    default: "full"
  target-url:
    description: "Target URL to run the tests against"
    required: true
  github-token:
    description: "Github token so we can update issues with reports"
    required: true
runs:
  using: "composite"
  steps:
    - name: ZAP Scan
      if: inputs.type == 'baseline'
      uses: zaproxy/action-baseline@v0.14.0
      with:
        token: ${{ inputs.github-token }}
        docker_name: "ghcr.io/zaproxy/zaproxy:stable"
        target: ${{ inputs.target-url }}
        cmd_options: "-a"
        issue_title: "ZAP Scan Baseline Report"
      continue-on-error: true
    - name: ZAP Scan Full
      if: inputs.type == 'full'
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        token: ${{ inputs.github-token }}
        docker_name: "ghcr.io/zaproxy/zaproxy:stable"
        target: ${{ inputs.target-url }}
        cmd_options: "-a"
        issue_title: "ZAP Full Scan Report"
      continue-on-error: true
